version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: 'teaster-wednester'
    volumes:
      - nest-home-backend:/Docker_Volumes/nest-home-backend
volumes:
  nest-home-backend:
